[package]
name = "rbfc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rbfc"
path = "src/lib/mod.rs"

[dependencies]
thiserror = "1.0.56"
